[package]
name        = "gc-crash"
description = "GameCube/Wii crash handler: register dump, stack trace, D-pad scrolling"
version.workspace    = true
authors.workspace    = true
edition.workspace    = true
license.workspace    = true

[dependencies]
gc-rt  = { path = "../gc-rt" }
gc-hal = { path = "../gc-hal" }
gc-gfx = { path = "../gc-gfx" }

[features]
default = []
wii = ["gc-rt/wii", "gc-hal/wii", "gc-gfx/wii"]
