[package]
name        = "hello_world"
description = "DevKit DOL — Hello World example for GameCube"
version.workspace    = true
authors.workspace    = true
edition.workspace    = true
license.workspace    = true

[dependencies]
dkdol-rt   = { path = "../../crates/dkdol-rt" }
dkdol-hal  = { path = "../../crates/dkdol-hal" }
dkdol-gfx  = { path = "../../crates/dkdol-gfx" }
