[package]
name = "vfs_demo"
version.workspace = true
edition.workspace = true

[dependencies]
dkdol-vfs = { path = "../../crates/dkdol-vfs", features = ["all-fs"] }
dkdol-gfx = { path = "../../crates/dkdol-gfx" }
dkdol-hal = { path = "../../crates/dkdol-hal" }
dkdol-rt  = { path = "../../crates/dkdol-rt" }
